### ISSUE TITLE
Shibboleth Authentication

### ISSUE THREAD

**Issue by hartloff** [daviddob/Autolab#1]

**Comment by daviddob** [comment]
Emails have been sent to several people over at EIS, hopefully someone gets back to me regarding next steps.

**Comment by daviddob** [comment]
Shibboleth is working via a workaround as the only attribute passed back currently is UID. Working with CIT to hopefully get more info out of it so we can have first/last/major/etc all populate automatically. Before semester starts ill refactor the login page to only support UB shibb auth.
