### ISSUE TITLE
Feature Request: Moss with flags

### ISSUE THREAD

**Issue by krivers** [daviddob/Autolab#17]
Hi there! I'm teaching 15-112, and I'd like to be able to run Moss with flags (specifically so that I can include a base file, so it stops getting flagged). It looks like the Autolab page for Moss is supposed to support this, but there isn't actually a text box I can enter information into under Step 2... any chance that that can be fixed?

Thanks!
- Kelly

**Comment by daviddob** [comment]
@krivers Sorry it took a bit to get back to you, under `Step 2 - Base File Tar` you can upload a tar of base files that will be ignored (no text box necessary) we essentially have options for all of the moss script parameters
