### ISSUE TITLE
Gradesheet Filtering not working

### ISSUE THREAD

**Issue by zsmoore** [daviddob/Autolab#18]
It looks like something that was recently pushed broke filtering on the grade sheet for an assignment.
Message me if you need any more info on it.

**Comment by zsmoore** [comment]
There is a base option to grade a single submission that will correctly filter the table. It might be possible to duplicate that functionality for all filtering.

**Comment by Searay-330** [comment]
the lecture and section fields where not marked as searchable but on the dev site it seems to be working after including them.

**Comment by zsmoore** [comment]
Looks to be working again.  Thanks @Searay-330 .
