### ISSUE TITLE
Lab section deadlines

### ISSUE THREAD

**Issue by hartloff** [daviddob/Autolab#2]
Assignments have an option to have different deadlines for each section of a course. Ideally there could also be different versions of the assignment so all lab sections do not have identical assignments.

**Comment by Searay-330** [comment]
addendum note could be possible to tie sections deadline to users when more than one user is needed per assignment on a given page otherwise grabbing the date per user is fine.

**Comment by Searay-330** [comment]
have completed this to my liking if anything else is needed we can reopen it.
