### ISSUE TITLE
Unable to regrade - gets 404 Page not found

### ISSUE THREAD

**Issue by rosecatherinek** [daviddob/Autolab#30]
Hi Team,

I am a TA for a course. I need to regrade a student's submission. For this, I go to:
Admin Options --> Manage Submissions --> Select the entry and click on the circular arrow that says - rerun the autograder on this submission. 

But, shows me this:
----------------------
Autolab
404 - Page not found
Oops! The page you are looking for could not be found.  
Autolab Home
Questions or problems? Please contact us.
----------------------

What could be the problem? Would you need additional info to fix this?

**Comment by daviddob** [comment]
Sorry to be the bearer of bad news, but you seem to have posted this issue on the fork of Autolab for use at University at Buffalo. While we would love to assist, our codebase does not currently suffer from this issue. That said, we have several features and bugfixes we would be more than willing to get merged into the CMU Autolab codebase should they have the time to do so in the future. Please let them know that while reconciling our codebases could be a large process, it could help with the issues they are currently seeing as well as add new features.

Here's a link to create an issue on the CMU side of things:
https://github.com/autolab/Autolab/issues/new

Thanks,
Dave

**Comment by rosecatherinek** [comment]
Thanks a lot, Dave! I didn't realize that these were different. Really sorry about that. I'll open this issue in the other repo.
